
---
deployment:
  tasks: 
    - export DEPLOYPATH=/home2/sazxjwte/public_html/website_14f8c164
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R fonts $DEPLOYPATH
    - /bin/cp  functions.php $DEPLOYPATH
    - /bin/cp  index.php $DEPLOYPATH
    - /bin/cp  collections.php $DEPLOYPATH
    - /bin/cp  purchase.php $DEPLOYPATH
    - /bin/cp  cart.php $DEPLOYPATH
    - /bin/cp  cart_2.php $DEPLOYPATH
    - /bin/cp  cart_handler.php $DEPLOYPATH
    